#!/usr/bin/env bash

for req in rsync; do
	command -v $req >/dev/null 2>&1 || {
		echo >&2 "$req required"
		exit 1
	}
done

cd "$(dirname "${BASH_SOURCE}")"

function sync() {
	rsync -q \
        --exclude ".git/" \
		--exclude ".DS_Store" \
		--exclude ".osx" \
		--exclude "Brewfile" \
		--exclude ".macos" \
		--exclude "install" \
		--exclude "README.md" \
		--exclude "LICENSE" \
		-avh --no-perms . ~
	source ~/.bash_profile
}

sync
unset sync
